import { readFile } from 'node:fs/promises'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'
import { readBinaryPlist } from './bplist-reader.js'
import { writeBinaryPlist } from './bplist-writer.js'

const FIXTURES_DIR = fileURLToPath(new URL('__fixtures__', import.meta.url))

describe('writeBinaryPlist', () => {
    describe('node-bplist-parser fixtures (write then read)', () => {
        // sourced from https://github.com/joeferner/node-bplist-parser/tree/master/test, MIT license
        it('iTunes Small', async () => {
            const file = await readFile(join(FIXTURES_DIR, 'iTunes-small.bplist'))
            const written = writeBinaryPlist(readBinaryPlist(file))
            const read = readBinaryPlist(written) as Record<string, unknown>

            expect(read['Application Version']).toBe('9.0.3')
            expect(read['Library Persistent ID']).toBe('6F81D37F95101437')
        })

        it('sample1', async () => {
            const file = await readFile(join(FIXTURES_DIR, 'sample1.bplist'))
            const written = writeBinaryPlist(readBinaryPlist(file))
            const read = readBinaryPlist(written) as Record<string, unknown>
            expect(read).toMatchInlineSnapshot(`
              {
                "CFBundleDevelopmentRegion": "English",
                "CFBundleIdentifier": "com.apple.dictionary.MySample",
                "CFBundleName": "MyDictionary",
                "CFBundleShortVersionString": "1.0",
                "DCSDictionaryCopyright": "Copyright Â© 2007 Apple Inc.",
                "DCSDictionaryDefaultPrefs": {
                  "display-column": "1",
                  "display-picture": "1",
                  "pronunciation": "0",
                  "version": "1",
                },
                "DCSDictionaryFrontMatterReferenceID": "front_back_matter",
                "DCSDictionaryManufacturerName": "Apple Inc.",
                "DCSDictionaryPrefsHTML": "MyDictionary_prefs.html",
                "DCSDictionaryXSL": "MyDictionary.xsl",
              }
            `)
        })

        it('sample2', async () => {
            const file = await readFile(join(FIXTURES_DIR, 'sample2.bplist'))
            const written = writeBinaryPlist(readBinaryPlist(file))
            const read = readBinaryPlist(written) as Record<string, unknown>
            expect(read).toMatchInlineSnapshot(`
              {
                "OptionsLabel": "Product",
                "PopupMenu": [
                  {
                    "Key": "iPhone",
                    "Title": "iPhone",
                  },
                  {
                    "Key": "iPad",
                    "Title": "iPad",
                  },
                  {
                    "Key": "
                      #import <Cocoa/Cocoa.h>

              #import <MacRuby/MacRuby.h>

              int main(int argc, char *argv[])
              {
                return macruby_main("rb_main.rb", argc, argv);
              }
              ",
                  },
                ],
                "TemplateSelection": {
                  "iPad": "Tab Bar iPad Application",
                  "iPhone": "Tab Bar iPhone Application",
                },
              }
            `)
        })

        it('airplay', async () => {
            const file = await readFile(join(FIXTURES_DIR, 'airplay.bplist'))
            const written = writeBinaryPlist(readBinaryPlist(file))
            const read = readBinaryPlist(written) as Record<string, unknown>
            expect(read).toMatchInlineSnapshot(`
              {
                "duration": 5555.0495,
                "loadedTimeRanges": [
                  {
                    "duration": 5555.0495,
                    "start": 0,
                  },
                ],
                "playbackBufferEmpty": true,
                "playbackBufferFull": false,
                "playbackLikelyToKeepUp": true,
                "position": 4.626998904,
                "rate": 1,
                "readyToPlay": true,
                "seekableTimeRanges": [
                  {
                    "duration": 5555.0495,
                    "start": 0,
                  },
                ],
              }
            `)
        })

        it('utf16', async () => {
            const file = await readFile(join(FIXTURES_DIR, 'utf16.bplist'))
            const written = writeBinaryPlist(readBinaryPlist(file))
            const read = readBinaryPlist(written) as Record<string, unknown>
            expect(read).toMatchInlineSnapshot(`
              {
                "BuildIdentifier": "rc1_build2",
                "BuildMachineOSBuild": "11E53",
                "CFBundleDevelopmentRegion": "en",
                "CFBundleDisplayName": "sellStuff",
                "CFBundleExecutable": "sellStuff",
                "CFBundleIconFile": "icon_57x57.png",
                "CFBundleIconFiles": [
                  "icon_57x57.png",
                  "icon_114x114.png",
                ],
                "CFBundleIdentifier": "com.sellStuff.iphone",
                "CFBundleInfoDictionaryVersion": "6.0",
                "CFBundleName": "sellStuff",
                "CFBundlePackageType": "APPL",
                "CFBundleResourceSpecification": "ResourceRules.plist",
                "CFBundleShortVersionString": "2.6.1",
                "CFBundleSignature": "????",
                "CFBundleSupportedPlatforms": [
                  "iPhoneOS",
                ],
                "CFBundleURLTypes": [
                  {
                    "CFBundleURLSchemes": [
                      "sellStuff",
                      "fb267453465127",
                    ],
                  },
                ],
                "CFBundleVersion": "2.6.1",
                "DTCompiler": "com.apple.compilers.llvm.clang.1_0",
                "DTPlatformBuild": "9B176",
                "DTPlatformName": "iphoneos",
                "DTPlatformVersion": "5.1",
                "DTSDKBuild": "9B176",
                "DTSDKName": "iphoneos5.1",
                "DTXcode": "0432",
                "DTXcodeBuild": "4E2002",
                "DistributionType": "AppStore",
                "MinimumOSVersion": "4.0",
                "NSHumanReadableCopyright": "©2008-2012, sellStuff, Inc.",
                "NSMainNibFile": "MainWindow",
                "UIDeviceFamily": [
                  1,
                ],
                "UIPrerenderedIcon": true,
                "UIRequiresPersistentWiFi": true,
              }
            `)
        })

        it('utf16chinese', async () => {
            const file = await readFile(join(FIXTURES_DIR, 'utf16_chinese.bplist'))
            const written = writeBinaryPlist(readBinaryPlist(file))
            const read = readBinaryPlist(written) as Record<string, unknown>
            expect(read.CFBundleName).toMatchInlineSnapshot('"天翼阅读"')
            expect(read.CFBundleDisplayName).toMatchInlineSnapshot('"天翼阅读"')
        })

        it('uid', async () => {
            const file = await readFile(join(FIXTURES_DIR, 'uid.bplist'))
            const written = writeBinaryPlist(readBinaryPlist(file, { preserveType: true }))
            const read = readBinaryPlist(written, { preserveType: true }) as Record<string, unknown>
            expect(read).toMatchInlineSnapshot(`
              {
                "$archiver": PlistValue {
                  "type": "ascii",
                  "value": "NSKeyedArchiver",
                },
                "$objects": [
                  PlistValue {
                    "type": "ascii",
                    "value": "$null",
                  },
                  {
                    "$class": PlistValue {
                      "type": "uid",
                      "value": 8,
                    },
                    "NS.keys": [
                      PlistValue {
                        "type": "uid",
                        "value": 2,
                      },
                      PlistValue {
                        "type": "uid",
                        "value": 3,
                      },
                      PlistValue {
                        "type": "uid",
                        "value": 4,
                      },
                    ],
                    "NS.objects": [
                      PlistValue {
                        "type": "uid",
                        "value": 5,
                      },
                      PlistValue {
                        "type": "uid",
                        "value": 6,
                      },
                      PlistValue {
                        "type": "uid",
                        "value": 7,
                      },
                    ],
                  },
                  PlistValue {
                    "type": "ascii",
                    "value": "key1",
                  },
                  PlistValue {
                    "type": "ascii",
                    "value": "key3",
                  },
                  PlistValue {
                    "type": "ascii",
                    "value": "key2",
                  },
                  PlistValue {
                    "type": "ascii",
                    "value": "obj1",
                  },
                  PlistValue {
                    "type": "ascii",
                    "value": "obj3",
                  },
                  PlistValue {
                    "type": "ascii",
                    "value": "obj2",
                  },
                  {
                    "$classes": [
                      PlistValue {
                        "type": "ascii",
                        "value": "NSMutableDictionary",
                      },
                      PlistValue {
                        "type": "ascii",
                        "value": "NSDictionary",
                      },
                      PlistValue {
                        "type": "ascii",
                        "value": "NSObject",
                      },
                    ],
                    "$classname": PlistValue {
                      "type": "ascii",
                      "value": "NSMutableDictionary",
                    },
                  },
                ],
                "$top": {
                  "root": PlistValue {
                    "type": "uid",
                    "value": 1,
                  },
                },
                "$version": PlistValue {
                  "type": "int",
                  "value": 100000,
                },
              }
            `)
        })

        it('int64', async () => {
            const file = await readFile(join(FIXTURES_DIR, 'int64.bplist'))
            const written = writeBinaryPlist(readBinaryPlist(file))
            const read = readBinaryPlist(written) as Record<string, unknown>
            expect(read).toMatchInlineSnapshot(`
              {
                "int32item": 1234567890,
                "int32itemsigned": -1234567890n,
                "int64item": 12345678901234567890n,
                "zero": 0,
              }
            `)
        })
    })

    it('plistlib fixture (write then read)', async () => {
        // sourced from https://github.com/python/cpython/blob/main/Lib/test/test_plistlib.py, PSF license
        const file = await readFile(join(FIXTURES_DIR, 'plistlib.bplist'))
        const written = writeBinaryPlist(readBinaryPlist(file))
        const read = readBinaryPlist(written) as Record<string, unknown>
        expect(read).toMatchInlineSnapshot(`
          {
            "aBigInt": 9223372036854775764n,
            "aBigInt2": 9223372036854775852n,
            "aDate": 2004-11-26T07:33:33.000Z,
            "aDict": {
              "aFalseValue": false,
              "aTrueValue": true,
              "aUnicodeValue": "Mässig, Maß",
              "anotherString": "<hello & 'hi' there!>",
              "deeperDict": {
                "a": 17,
                "b": 32.5,
                "c": [
                  1,
                  2,
                  "text",
                ],
              },
            },
            "aFloat": 0.5,
            "aList": [
              "A",
              "B",
              12,
              32.5,
              [
                1,
                2,
                3,
              ],
            ],
            "aNegativeBigInt": -80000000000n,
            "aNegativeInt": -5n,
            "aString": "Doodah",
            "anEmptyDict": {},
            "anEmptyList": [],
            "anInt": 728,
            "nestedData": [
              Uint8Array [
                60,
                108,
                111,
                116,
                115,
                32,
                111,
                102,
                32,
                98,
                105,
                110,
                97,
                114,
                121,
                32,
                103,
                117,
                110,
                107,
                62,
                0,
                1,
                2,
                3,
                60,
                108,
                111,
                116,
                115,
                32,
                111,
                102,
                32,
                98,
                105,
                110,
                97,
                114,
                121,
                32,
                103,
                117,
                110,
                107,
                62,
                0,
                1,
                2,
                3,
                60,
                108,
                111,
                116,
                115,
                32,
                111,
                102,
                32,
                98,
                105,
                110,
                97,
                114,
                121,
                32,
                103,
                117,
                110,
                107,
                62,
                0,
                1,
                2,
                3,
                60,
                108,
                111,
                116,
                115,
                32,
                111,
                102,
                32,
                98,
                105,
                110,
                97,
                114,
                121,
                32,
                103,
                117,
                110,
                107,
                62,
                0,
                1,
                2,
                3,
                60,
                108,
                111,
                116,
                115,
                32,
                111,
                102,
                32,
                98,
                105,
                110,
                97,
                114,
                121,
                32,
                103,
                117,
                110,
                107,
                62,
                0,
                1,
                2,
                3,
                60,
                108,
                111,
                116,
                115,
                32,
                111,
                102,
                32,
                98,
                105,
                110,
                97,
                114,
                121,
                32,
                103,
                117,
                110,
                107,
                62,
                0,
                1,
                2,
                3,
                60,
                108,
                111,
                116,
                115,
                32,
                111,
                102,
                32,
                98,
                105,
                110,
                97,
                114,
                121,
                32,
                103,
                117,
                110,
                107,
                62,
                0,
                1,
                2,
                3,
                60,
                108,
                111,
                116,
                115,
                32,
                111,
                102,
                32,
                98,
                105,
                110,
                97,
                114,
                121,
                32,
                103,
                117,
                110,
                107,
                62,
                0,
                1,
                2,
                3,
                60,
                108,
                111,
                116,
                115,
                32,
                111,
                102,
                32,
                98,
                105,
                110,
                97,
                114,
                121,
                32,
                103,
                117,
                110,
                107,
                62,
                0,
                1,
                2,
                3,
                60,
                108,
                111,
                116,
                115,
                32,
                111,
                102,
                32,
                98,
                105,
                110,
                97,
                114,
                121,
                32,
                103,
                117,
                110,
                107,
                62,
                0,
                1,
                2,
                3,
              ],
            ],
            "someData": Uint8Array [
              60,
              98,
              105,
              110,
              97,
              114,
              121,
              32,
              103,
              117,
              110,
              107,
              62,
            ],
            "someMoreData": Uint8Array [
              60,
              108,
              111,
              116,
              115,
              32,
              111,
              102,
              32,
              98,
              105,
              110,
              97,
              114,
              121,
              32,
              103,
              117,
              110,
              107,
              62,
              0,
              1,
              2,
              3,
              60,
              108,
              111,
              116,
              115,
              32,
              111,
              102,
              32,
              98,
              105,
              110,
              97,
              114,
              121,
              32,
              103,
              117,
              110,
              107,
              62,
              0,
              1,
              2,
              3,
              60,
              108,
              111,
              116,
              115,
              32,
              111,
              102,
              32,
              98,
              105,
              110,
              97,
              114,
              121,
              32,
              103,
              117,
              110,
              107,
              62,
              0,
              1,
              2,
              3,
              60,
              108,
              111,
              116,
              115,
              32,
              111,
              102,
              32,
              98,
              105,
              110,
              97,
              114,
              121,
              32,
              103,
              117,
              110,
              107,
              62,
              0,
              1,
              2,
              3,
              60,
              108,
              111,
              116,
              115,
              32,
              111,
              102,
              32,
              98,
              105,
              110,
              97,
              114,
              121,
              32,
              103,
              117,
              110,
              107,
              62,
              0,
              1,
              2,
              3,
              60,
              108,
              111,
              116,
              115,
              32,
              111,
              102,
              32,
              98,
              105,
              110,
              97,
              114,
              121,
              32,
              103,
              117,
              110,
              107,
              62,
              0,
              1,
              2,
              3,
              60,
              108,
              111,
              116,
              115,
              32,
              111,
              102,
              32,
              98,
              105,
              110,
              97,
              114,
              121,
              32,
              103,
              117,
              110,
              107,
              62,
              0,
              1,
              2,
              3,
              60,
              108,
              111,
              116,
              115,
              32,
              111,
              102,
              32,
              98,
              105,
              110,
              97,
              114,
              121,
              32,
              103,
              117,
              110,
              107,
              62,
              0,
              1,
              2,
              3,
              60,
              108,
              111,
              116,
              115,
              32,
              111,
              102,
              32,
              98,
              105,
              110,
              97,
              114,
              121,
              32,
              103,
              117,
              110,
              107,
              62,
              0,
              1,
              2,
              3,
              60,
              108,
              111,
              116,
              115,
              32,
              111,
              102,
              32,
              98,
              105,
              110,
              97,
              114,
              121,
              32,
              103,
              117,
              110,
              107,
              62,
              0,
              1,
              2,
              3,
            ],
            "Åbenraa": "That was a unicode key.",
          }
        `)
    })
})
